
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    [System.Flags]
    public enum ActionPointType
    {
        /// <summary>
        /// //空
        /// </summary>
        None = 0,
        /// <summary>
        /// //造成伤害前
        /// </summary>
        PreCauseDamage = 2,
        /// <summary>
        /// //承受伤害前
        /// </summary>
        PreReceiveDamage = 4,
        /// <summary>
        /// //造成伤害后
        /// </summary>
        PostCauseDamage = 8,
        /// <summary>
        /// //承受伤害后
        /// </summary>
        PostReceiveDamage = 16,
        /// <summary>
        /// //给予治疗后
        /// </summary>
        PostGiveCure = 32,
        /// <summary>
        /// //接受治疗后
        /// </summary>
        PostReceiveCure = 64,
        /// <summary>
        /// //赋给状态前
        /// </summary>
        PreGiveStatus = 128,
        /// <summary>
        /// //承受状态前
        /// </summary>
        PreReceiveStatus = 256,
        /// <summary>
        /// //赋加状态后
        /// </summary>
        PostGiveStatus = 512,
        /// <summary>
        /// //承受状态后
        /// </summary>
        PostReceiveStatus = 1024,
        /// <summary>
        /// //施放技能前
        /// </summary>
        PreSpell = 2048,
        /// <summary>
        /// //施放技能后
        /// </summary>
        PostSpell = 4096,
        /// <summary>
        /// //致死预判后、扣血前（受击者，可改伤害免死）
        /// </summary>
        PreBeKilled = 8192,
        /// <summary>
        /// //确认仍致死、扣血前（攻击者 onKill）
        /// </summary>
        PreCauseKill = 16384,
        /// <summary>
        /// //确认仍致死、扣血前（受击者 beKilled）
        /// </summary>
        PreReceiveKill = 32768,
        /// <summary>
        /// //卸 Buff 前（仅正在卸的那条 TriggerBuff 开火）
        /// </summary>
        PreRemoveStatus = 65536,
    }

} 

