
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    [System.Flags]
    public enum ActionControlType
    {
        /// <summary>
        /// //无调整
        /// </summary>
        None = 0,
        /// <summary>
        /// 移动禁止
        /// </summary>
        MoveForbid = 1,
        /// <summary>
        /// 闪避禁止
        /// </summary>
        RollForbid = 2,
        /// <summary>
        /// 攻击禁止
        /// </summary>
        AttackForbid = 4,
        /// <summary>
        /// 伤害禁止
        /// </summary>
        AttackDamageForbid = 8,
    }

} 

