
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum AdditionalCondition
    {
        /// <summary>
        /// 无条件
        /// </summary>
        None = 0,
        /// <summary>
        /// 同属性
        /// </summary>
        SameAttribute = 1,
        /// <summary>
        /// 同阵营
        /// </summary>
        SameFaction = 2,
        /// <summary>
        /// 同属性或同阵营
        /// </summary>
        AttributeOrFaction = 3,
    }

} 

