
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    [System.Flags]
    public enum BuffType
    {
        /// <summary>
        /// //无类型，由主动技能增加与移除
        /// </summary>
        None = 0,
        /// <summary>
        /// //时间类型Buff
        /// </summary>
        TimeBuff = 1,
        /// <summary>
        /// //次数类型Buff
        /// </summary>
        NumberBuff = 2,
        /// <summary>
        /// //有触发器Buff
        /// </summary>
        TriggerBuff = 4,
        /// <summary>
        /// //有移除触发器Buff
        /// </summary>
        RemoveTriggerBuff = 8,
        /// <summary>
        /// //有触发冷却的Buff
        /// </summary>
        CDBuff = 16,
    }

} 

