
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public partial class BuffDemoReader
{
    private readonly System.Collections.Generic.Dictionary<int, BuffDemoSetting> _dataMap;
    private readonly System.Collections.Generic.List<BuffDemoSetting> _dataList;
    
    public BuffDemoReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffDemoSetting>(count);
        _dataList = new System.Collections.Generic.List<BuffDemoSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuffDemoSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.BuffDemoSetting.DeserializeBuffDemoSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.BuffId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffDemoSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffDemoSetting> DataList => _dataList;

    public BuffDemoSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BuffDemoSetting Get(int key) => _dataMap[key];
    public BuffDemoSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

