
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class BuffDemoSetting : Luban.BeanBase
{
    public BuffDemoSetting(JSONNode _buf) 
    {
        { if(!_buf["BuffId"].IsNumber) { throw new SerializationException(); }  BuffId = _buf["BuffId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["BuffType"].IsNumber) { throw new SerializationException(); }  BuffType = (BuffType)_buf["BuffType"].AsInt; }
        { if(!_buf["BigBuffType"].IsNumber) { throw new SerializationException(); }  BigBuffType = _buf["BigBuffType"]; }
        { if(!_buf["SmallBuffType"].IsNumber) { throw new SerializationException(); }  SmallBuffType = _buf["SmallBuffType"]; }
        { var __json0 = _buf["BuffTag"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffTag = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  BuffTag.Add(__v0); }   }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["StatusSlot"].IsNumber) { throw new SerializationException(); }  StatusSlot = _buf["StatusSlot"]; }
        { if(!_buf["CanStack"].IsNumber) { throw new SerializationException(); }  CanStack = _buf["CanStack"]; }
        { if(!_buf["MaxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["MaxLevel"]; }
        { if(!_buf["RepeatedAddition"].IsNumber) { throw new SerializationException(); }  RepeatedAddition = _buf["RepeatedAddition"]; }
        { var __json0 = _buf["BuffModifyList"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffModifyList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuffModifyList.Add(__v0); }   }
        { if(!_buf["BaseDuration"].IsNumber) { throw new SerializationException(); }  BaseDuration = _buf["BaseDuration"]; }
        { if(!_buf["BaseTimes"].IsNumber) { throw new SerializationException(); }  BaseTimes = _buf["BaseTimes"]; }
        { if(!_buf["IsAddPoint"].IsNumber) { throw new SerializationException(); }  IsAddPoint = _buf["IsAddPoint"]; }
        { if(!_buf["ActionPointType"].IsNumber) { throw new SerializationException(); }  ActionPointType = (ActionPointType)_buf["ActionPointType"].AsInt; }
        { if(!_buf["CDTime"].IsNumber) { throw new SerializationException(); }  CDTime = _buf["CDTime"]; }
        { if(!_buf["DelayTime"].IsNumber) { throw new SerializationException(); }  DelayTime = _buf["DelayTime"]; }
        { if(!_buf["IntervalTime"].IsNumber) { throw new SerializationException(); }  IntervalTime = _buf["IntervalTime"]; }
        { if(!_buf["TriggerFormula"].IsString) { throw new SerializationException(); }  TriggerFormula = _buf["TriggerFormula"]; }
        { if(!_buf["RemoveActionPointType"].IsNumber) { throw new SerializationException(); }  RemoveActionPointType = (ActionPointType)_buf["RemoveActionPointType"].AsInt; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
    }

    public static BuffDemoSetting DeserializeBuffDemoSetting(JSONNode _buf)
    {
        return new BuffDemoSetting(_buf);
    }

    /// <summary>
    /// BuffId
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Buff类型
    /// </summary>
    public readonly BuffType BuffType;
    /// <summary>
    /// Buff大类型
    /// </summary>
    public readonly int BigBuffType;
    /// <summary>
    /// Buff细分类型
    /// </summary>
    public readonly int SmallBuffType;
    /// <summary>
    /// Buff标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> BuffTag;
    /// <summary>
    /// Buff描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 显示在状态栏
    /// </summary>
    public readonly int StatusSlot;
    /// <summary>
    /// 能否叠加
    /// </summary>
    public readonly int CanStack;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 重复添加时的处理
    /// </summary>
    public readonly int RepeatedAddition;
    /// <summary>
    /// Buff效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffModifyList;
    /// <summary>
    /// Buff默认时长
    /// </summary>
    public readonly float BaseDuration;
    /// <summary>
    /// Buff默认次数
    /// </summary>
    public readonly int BaseTimes;
    /// <summary>
    /// 是否加入时触发
    /// </summary>
    public readonly int IsAddPoint;
    /// <summary>
    /// Buff触发点
    /// </summary>
    public readonly ActionPointType ActionPointType;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float CDTime;
    /// <summary>
    /// 延迟触发时间
    /// </summary>
    public readonly float DelayTime;
    /// <summary>
    /// 间隔触发时间
    /// </summary>
    public readonly float IntervalTime;
    /// <summary>
    /// Buff触发条件判断
    /// </summary>
    public readonly string TriggerFormula;
    /// <summary>
    /// Buff移除触发点
    /// </summary>
    public readonly ActionPointType RemoveActionPointType;
    /// <summary>
    /// Buff优先级
    /// </summary>
    public readonly int Priority;
   
    public const int __ID__ = 1895923834;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BuffId:" + BuffId + ","
        + "Name:" + Name + ","
        + "BuffType:" + BuffType + ","
        + "BigBuffType:" + BigBuffType + ","
        + "SmallBuffType:" + SmallBuffType + ","
        + "BuffTag:" + Luban.StringUtil.CollectionToString(BuffTag) + ","
        + "Description:" + Description + ","
        + "StatusSlot:" + StatusSlot + ","
        + "CanStack:" + CanStack + ","
        + "MaxLevel:" + MaxLevel + ","
        + "RepeatedAddition:" + RepeatedAddition + ","
        + "BuffModifyList:" + Luban.StringUtil.CollectionToString(BuffModifyList) + ","
        + "BaseDuration:" + BaseDuration + ","
        + "BaseTimes:" + BaseTimes + ","
        + "IsAddPoint:" + IsAddPoint + ","
        + "ActionPointType:" + ActionPointType + ","
        + "CDTime:" + CDTime + ","
        + "DelayTime:" + DelayTime + ","
        + "IntervalTime:" + IntervalTime + ","
        + "TriggerFormula:" + TriggerFormula + ","
        + "RemoveActionPointType:" + RemoveActionPointType + ","
        + "Priority:" + Priority + ","
        + "}";
    }
}
}

