
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class BuffModifySetting : Luban.BeanBase
{
    public BuffModifySetting(JSONNode _buf) 
    {
        { if(!_buf["EffectModifyID"].IsNumber) { throw new SerializationException(); }  EffectModifyID = _buf["EffectModifyID"]; }
        { if(!_buf["EffectModifyType"].IsNumber) { throw new SerializationException(); }  EffectModifyType = (EffectModifyType)_buf["EffectModifyType"].AsInt; }
        { if(!_buf["ParamInt1"].IsNumber) { throw new SerializationException(); }  ParamInt1 = _buf["ParamInt1"]; }
        { if(!_buf["ParamInt2"].IsNumber) { throw new SerializationException(); }  ParamInt2 = _buf["ParamInt2"]; }
        { if(!_buf["ParamInt3"].IsNumber) { throw new SerializationException(); }  ParamInt3 = _buf["ParamInt3"]; }
        { if(!_buf["ParamFloat1"].IsNumber) { throw new SerializationException(); }  ParamFloat1 = _buf["ParamFloat1"]; }
        { if(!_buf["ParamFloat2"].IsNumber) { throw new SerializationException(); }  ParamFloat2 = _buf["ParamFloat2"]; }
        { var __json0 = _buf["ParamString1"]; if(!__json0.IsArray) { throw new SerializationException(); } ParamString1 = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ParamString1.Add(__v0); }   }
    }

    public static BuffModifySetting DeserializeBuffModifySetting(JSONNode _buf)
    {
        return new BuffModifySetting(_buf);
    }

    /// <summary>
    /// 效果ID
    /// </summary>
    public readonly int EffectModifyID;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly EffectModifyType EffectModifyType;
    /// <summary>
    /// Int参数1
    /// </summary>
    public readonly int ParamInt1;
    /// <summary>
    /// Int参数2
    /// </summary>
    public readonly int ParamInt2;
    /// <summary>
    /// Int参数3
    /// </summary>
    public readonly int ParamInt3;
    /// <summary>
    /// Float参数1
    /// </summary>
    public readonly float ParamFloat1;
    /// <summary>
    /// Float参数2
    /// </summary>
    public readonly float ParamFloat2;
    public readonly System.Collections.Generic.List<string> ParamString1;
   
    public const int __ID__ = 611272323;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "EffectModifyID:" + EffectModifyID + ","
        + "EffectModifyType:" + EffectModifyType + ","
        + "ParamInt1:" + ParamInt1 + ","
        + "ParamInt2:" + ParamInt2 + ","
        + "ParamInt3:" + ParamInt3 + ","
        + "ParamFloat1:" + ParamFloat1 + ","
        + "ParamFloat2:" + ParamFloat2 + ","
        + "ParamString1:" + Luban.StringUtil.CollectionToString(ParamString1) + ","
        + "}";
    }
}
}

