
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
/// <summary>
/// 角色 4 战斗键 Idle 入口
/// </summary>
public partial class CharacterSlotReader
{
    private readonly System.Collections.Generic.List<CharacterSlotSetting> _dataList;

    private System.Collections.Generic.Dictionary<(int, CombatButton, CombatPress, int, int), CharacterSlotSetting> _dataMapUnion;

    public CharacterSlotReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<CharacterSlotSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterSlotSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.CharacterSlotSetting.DeserializeCharacterSlotSetting(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, CombatButton, CombatPress, int, int), CharacterSlotSetting>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.CharacterId, _v.Button, _v.Press, _v.FormId, _v.Priority), _v);
        }
    }

    public System.Collections.Generic.List<CharacterSlotSetting> DataList => _dataList;

    public CharacterSlotSetting Get(int CharacterId, CombatButton Button, CombatPress Press, int FormId, int Priority) => _dataMapUnion.TryGetValue((CharacterId, Button, Press, FormId, Priority), out CharacterSlotSetting __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

