
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class CharacterSlotSetting : Luban.BeanBase
{
    public CharacterSlotSetting(JSONNode _buf) 
    {
        { if(!_buf["CharacterId"].IsNumber) { throw new SerializationException(); }  CharacterId = _buf["CharacterId"]; }
        { if(!_buf["Button"].IsNumber) { throw new SerializationException(); }  Button = (CombatButton)_buf["Button"].AsInt; }
        { if(!_buf["Press"].IsNumber) { throw new SerializationException(); }  Press = (CombatPress)_buf["Press"].AsInt; }
        { if(!_buf["FormId"].IsNumber) { throw new SerializationException(); }  FormId = _buf["FormId"]; }
        { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }
        { var __json0 = _buf["RequiredTags"]; if(!__json0.IsArray) { throw new SerializationException(); } RequiredTags = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  RequiredTags.Add(__v0); }   }
        { if(!_buf["SkillId"].IsNumber) { throw new SerializationException(); }  SkillId = _buf["SkillId"]; }
        { if(!_buf["EmpoweredSkillId"].IsNumber) { throw new SerializationException(); }  EmpoweredSkillId = _buf["EmpoweredSkillId"]; }
    }

    public static CharacterSlotSetting DeserializeCharacterSlotSetting(JSONNode _buf)
    {
        return new CharacterSlotSetting(_buf);
    }

    /// <summary>
    /// 角色Id
    /// </summary>
    public readonly int CharacterId;
    /// <summary>
    /// 战斗键
    /// </summary>
    public readonly CombatButton Button;
    /// <summary>
    /// 按法
    /// </summary>
    public readonly CombatPress Press;
    /// <summary>
    /// 形态
    /// </summary>
    public readonly int FormId;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 所需 Tag
    /// </summary>
    public readonly System.Collections.Generic.List<string> RequiredTags;
    /// <summary>
    /// 入口技能
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// EX 技能
    /// </summary>
    public readonly int EmpoweredSkillId;
   
    public const int __ID__ = 894951337;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CharacterId:" + CharacterId + ","
        + "Button:" + Button + ","
        + "Press:" + Press + ","
        + "FormId:" + FormId + ","
        + "Priority:" + Priority + ","
        + "RequiredTags:" + Luban.StringUtil.CollectionToString(RequiredTags) + ","
        + "SkillId:" + SkillId + ","
        + "EmpoweredSkillId:" + EmpoweredSkillId + ","
        + "}";
    }
}
}

