
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class CharacterKitSetting : Luban.BeanBase
{
    public CharacterKitSetting(JSONNode _buf) 
    {
        { if(!_buf["CharacterId"].IsNumber) { throw new SerializationException(); }  CharacterId = _buf["CharacterId"]; }
        { if(!_buf["Attribute"].IsString) { throw new SerializationException(); }  Attribute = _buf["Attribute"]; }
        { if(!_buf["Faction"].IsString) { throw new SerializationException(); }  Faction = _buf["Faction"]; }
        { if(!_buf["CombatRole"].IsString) { throw new SerializationException(); }  CombatRole = _buf["CombatRole"]; }
        { if(!_buf["CorePassiveSkillId"].IsNumber) { throw new SerializationException(); }  CorePassiveSkillId = _buf["CorePassiveSkillId"]; }
        { if(!_buf["AdditionalAbilitySkillId"].IsNumber) { throw new SerializationException(); }  AdditionalAbilitySkillId = _buf["AdditionalAbilitySkillId"]; }
        { if(!_buf["AdditionalCondition"].IsNumber) { throw new SerializationException(); }  AdditionalCondition = (AdditionalCondition)_buf["AdditionalCondition"].AsInt; }
        { var __json0 = _buf["ExtraPassiveSkillIds"]; if(!__json0.IsArray) { throw new SerializationException(); } ExtraPassiveSkillIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ExtraPassiveSkillIds.Add(__v0); }   }
        { if(!_buf["DefaultFormId"].IsNumber) { throw new SerializationException(); }  DefaultFormId = _buf["DefaultFormId"]; }
        { if(!_buf["ChainSkillId"].IsNumber) { throw new SerializationException(); }  ChainSkillId = _buf["ChainSkillId"]; }
        { if(!_buf["QuickAssistSkillId"].IsNumber) { throw new SerializationException(); }  QuickAssistSkillId = _buf["QuickAssistSkillId"]; }
        { if(!_buf["DefensiveAssistSkillId"].IsNumber) { throw new SerializationException(); }  DefensiveAssistSkillId = _buf["DefensiveAssistSkillId"]; }
        { if(!_buf["EvasiveAssistSkillId"].IsNumber) { throw new SerializationException(); }  EvasiveAssistSkillId = _buf["EvasiveAssistSkillId"]; }
        { if(!_buf["AssistFollowUpSkillId"].IsNumber) { throw new SerializationException(); }  AssistFollowUpSkillId = _buf["AssistFollowUpSkillId"]; }
        { if(!_buf["HarmonyBreakSkillId"].IsNumber) { throw new SerializationException(); }  HarmonyBreakSkillId = _buf["HarmonyBreakSkillId"]; }
    }

    public static CharacterKitSetting DeserializeCharacterKitSetting(JSONNode _buf)
    {
        return new CharacterKitSetting(_buf);
    }

    /// <summary>
    /// 角色Id
    /// </summary>
    public readonly int CharacterId;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly string Attribute;
    /// <summary>
    /// 阵营
    /// </summary>
    public readonly string Faction;
    /// <summary>
    /// 定位
    /// </summary>
    public readonly string CombatRole;
    /// <summary>
    /// 核心被动 SkillId
    /// </summary>
    public readonly int CorePassiveSkillId;
    /// <summary>
    /// 额外能力 SkillId
    /// </summary>
    public readonly int AdditionalAbilitySkillId;
    /// <summary>
    /// 额外能力条件
    /// </summary>
    public readonly AdditionalCondition AdditionalCondition;
    /// <summary>
    /// 额外被动列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ExtraPassiveSkillIds;
    /// <summary>
    /// 默认形态
    /// </summary>
    public readonly int DefaultFormId;
    /// <summary>
    /// Z+失衡窗连携
    /// </summary>
    public readonly int ChainSkillId;
    /// <summary>
    /// Z+支援窗
    /// </summary>
    public readonly int QuickAssistSkillId;
    /// <summary>
    /// Z+黄闪招架
    /// </summary>
    public readonly int DefensiveAssistSkillId;
    /// <summary>
    /// Z+红闪回避
    /// </summary>
    public readonly int EvasiveAssistSkillId;
    /// <summary>
    /// 招架/回避后派生
    /// </summary>
    public readonly int AssistFollowUpSkillId;
    /// <summary>
    /// F谐度破坏 SkillId
    /// </summary>
    public readonly int HarmonyBreakSkillId;
   
    public const int __ID__ = -828896637;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CharacterId:" + CharacterId + ","
        + "Attribute:" + Attribute + ","
        + "Faction:" + Faction + ","
        + "CombatRole:" + CombatRole + ","
        + "CorePassiveSkillId:" + CorePassiveSkillId + ","
        + "AdditionalAbilitySkillId:" + AdditionalAbilitySkillId + ","
        + "AdditionalCondition:" + AdditionalCondition + ","
        + "ExtraPassiveSkillIds:" + Luban.StringUtil.CollectionToString(ExtraPassiveSkillIds) + ","
        + "DefaultFormId:" + DefaultFormId + ","
        + "ChainSkillId:" + ChainSkillId + ","
        + "QuickAssistSkillId:" + QuickAssistSkillId + ","
        + "DefensiveAssistSkillId:" + DefensiveAssistSkillId + ","
        + "EvasiveAssistSkillId:" + EvasiveAssistSkillId + ","
        + "AssistFollowUpSkillId:" + AssistFollowUpSkillId + ","
        + "HarmonyBreakSkillId:" + HarmonyBreakSkillId + ","
        + "}";
    }
}
}

