
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
/// <summary>
/// 角色招式包：被动 + Z 响应技
/// </summary>
public partial class CharacterKitReader
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterKitSetting> _dataMap;
    private readonly System.Collections.Generic.List<CharacterKitSetting> _dataList;
    
    public CharacterKitReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterKitSetting>(count);
        _dataList = new System.Collections.Generic.List<CharacterKitSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterKitSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.CharacterKitSetting.DeserializeCharacterKitSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterKitSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterKitSetting> DataList => _dataList;

    public CharacterKitSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterKitSetting Get(int key) => _dataMap[key];
    public CharacterKitSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

