
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum CombatPress
    {
        /// <summary>
        /// 点按；与运行时 PressType.Click 对应
        /// </summary>
        Click = 0,
        /// <summary>
        /// 长按；与运行时 PressType.LongPress 对应
        /// </summary>
        Hold = 1,
    }

} 

