
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum CombatButton
    {
        /// <summary>
        /// 普攻键 ButtonX
        /// </summary>
        Attack = 0,
        /// <summary>
        /// 战技键 ButtonB
        /// </summary>
        Skill = 1,
        /// <summary>
        /// 闪避键 ButtonY
        /// </summary>
        Dodge = 2,
        /// <summary>
        /// 终结技键 ButtonA
        /// </summary>
        Ultimate = 3,
    }

} 

