
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum DamageType
    {
        /// <summary>
        /// 物理
        /// </summary>
        Physic = 0,
        /// <summary>
        /// 火
        /// </summary>
        Fire = 1,
        /// <summary>
        /// 冰
        /// </summary>
        Ice = 2,
        /// <summary>
        /// 电
        /// </summary>
        Electric = 3,
        /// <summary>
        /// 真实
        /// </summary>
        Real = 4,
    }

} 

