
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class DazeSetting : Luban.BeanBase
{
    public DazeSetting(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["MaxDaze"].IsNumber) { throw new SerializationException(); }  MaxDaze = _buf["MaxDaze"]; }
        { if(!_buf["HoldSeconds"].IsNumber) { throw new SerializationException(); }  HoldSeconds = _buf["HoldSeconds"]; }
        { if(!_buf["DurationSeconds"].IsNumber) { throw new SerializationException(); }  DurationSeconds = _buf["DurationSeconds"]; }
        { if(!_buf["VulnBonus"].IsNumber) { throw new SerializationException(); }  VulnBonus = _buf["VulnBonus"]; }
        { if(!_buf["ChainCount"].IsNumber) { throw new SerializationException(); }  ChainCount = _buf["ChainCount"]; }
        { if(!_buf["RecoverIFrame"].IsNumber) { throw new SerializationException(); }  RecoverIFrame = _buf["RecoverIFrame"]; }
        { if(!_buf["DazeResist"].IsNumber) { throw new SerializationException(); }  DazeResist = _buf["DazeResist"]; }
        { if(!_buf["IdleRegenPerSec"].IsNumber) { throw new SerializationException(); }  IdleRegenPerSec = _buf["IdleRegenPerSec"]; }
        { if(!_buf["CanDaze"].IsNumber) { throw new SerializationException(); }  CanDaze = _buf["CanDaze"]; }
        { if(!_buf["ParryDazeRatio"].IsNumber) { throw new SerializationException(); }  ParryDazeRatio = _buf["ParryDazeRatio"]; }
    }

    public static DazeSetting DeserializeDazeSetting(JSONNode _buf)
    {
        return new DazeSetting(_buf);
    }

    /// <summary>
    /// 档位Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 失衡上限
    /// </summary>
    public readonly float MaxDaze;
    /// <summary>
    /// 破衡后停条秒
    /// </summary>
    public readonly float HoldSeconds;
    /// <summary>
    /// 随后掉条秒
    /// </summary>
    public readonly float DurationSeconds;
    /// <summary>
    /// 失衡易伤
    /// </summary>
    public readonly float VulnBonus;
    /// <summary>
    /// 连携次数
    /// </summary>
    public readonly int ChainCount;
    /// <summary>
    /// 起身无敌秒
    /// </summary>
    public readonly float RecoverIFrame;
    /// <summary>
    /// 失衡抗性0-1
    /// </summary>
    public readonly float DazeResist;
    /// <summary>
    /// 非失衡每秒回复比例
    /// </summary>
    public readonly float IdleRegenPerSec;
    /// <summary>
    /// 1=可失衡
    /// </summary>
    public readonly int CanDaze;
    /// <summary>
    /// 招架失衡倍率
    /// </summary>
    public readonly float ParryDazeRatio;
   
    public const int __ID__ = -1700882264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "MaxDaze:" + MaxDaze + ","
        + "HoldSeconds:" + HoldSeconds + ","
        + "DurationSeconds:" + DurationSeconds + ","
        + "VulnBonus:" + VulnBonus + ","
        + "ChainCount:" + ChainCount + ","
        + "RecoverIFrame:" + RecoverIFrame + ","
        + "DazeResist:" + DazeResist + ","
        + "IdleRegenPerSec:" + IdleRegenPerSec + ","
        + "CanDaze:" + CanDaze + ","
        + "ParryDazeRatio:" + ParryDazeRatio + ","
        + "}";
    }
}
}

