
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public partial class DazeSettingReader
{
    private readonly System.Collections.Generic.Dictionary<int, DazeSetting> _dataMap;
    private readonly System.Collections.Generic.List<DazeSetting> _dataList;
    
    public DazeSettingReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, DazeSetting>(count);
        _dataList = new System.Collections.Generic.List<DazeSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DazeSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.DazeSetting.DeserializeDazeSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DazeSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<DazeSetting> DataList => _dataList;

    public DazeSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DazeSetting Get(int key) => _dataMap[key];
    public DazeSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

