
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum EffectRemoveType
    {
        /// <summary>
        /// //不主动移除
        /// </summary>
        None = 0,
        /// <summary>
        /// //时间到了
        /// </summary>
        TimeOut = 1,
        /// <summary>
        /// //次数到了
        /// </summary>
        NumberClear = 2,
        /// <summary>
        /// //走触发器
        /// </summary>
        Trigger = 3,
        /// <summary>
        /// //特殊条件，走Update判断
        /// </summary>
        SpeicalUpdate = 4,
    }

} 

