
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum EffectModifyType
    {
        /// <summary>
        /// //修饰玩家的属性
        /// </summary>
        PlayerModify = 1,
        /// <summary>
        /// //玩家行为禁制
        /// </summary>
        PlayerControll = 2,
        /// <summary>
        /// //修饰Buff属性的（如影响Buff层最大层数，Buff基础伤害值等）
        /// </summary>
        BuffModify = 3,
        /// <summary>
        /// //减去属性（这里和上面Modify是不一样的，Damage和Curve是不可回溯的，直接减去或添加）
        /// </summary>
        DamageEffect = 4,
        /// <summary>
        /// //添加属性
        /// </summary>
        CurveEffect = 5,
        /// <summary>
        /// //施加Buff
        /// </summary>
        AddStatus = 7,
        /// <summary>
        /// //移除Buff
        /// </summary>
        RemoveStatus = 8,
        /// <summary>
        /// //技能伤害
        /// </summary>
        SkillHpDamage = 9,
        /// <summary>
        /// //Buff伤害
        /// </summary>
        BuffHpDamage = 10,
        /// <summary>
        /// //技能带来的资源变化
        /// </summary>
        SkillResource = 11,
        /// <summary>
        /// //Buff带来的资源变化
        /// </summary>
        BuffResource = 12,
        SkillAddStatus = 13,
        BuffAddStatus = 14,
    }

} 

