
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum EffectAutoTriggerType
    {
        /// <summary>
        /// //空
        /// </summary>
        None = 0,
        /// <summary>
        /// //能力激活时生效
        /// </summary>
        Instant = 1,
        /// <summary>
        /// //按行动点事件
        /// </summary>
        Action = 2,
        /// <summary>
        /// //按计时状态事件
        /// </summary>
        Condition = 3,
    }

} 

