
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public partial class FormulaTypeReader
{
    private readonly System.Collections.Generic.Dictionary<int, FormulaTypeSetting> _dataMap;
    private readonly System.Collections.Generic.List<FormulaTypeSetting> _dataList;
    
    public FormulaTypeReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, FormulaTypeSetting>(count);
        _dataList = new System.Collections.Generic.List<FormulaTypeSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            FormulaTypeSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.FormulaTypeSetting.DeserializeFormulaTypeSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.FormulaID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FormulaTypeSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<FormulaTypeSetting> DataList => _dataList;

    public FormulaTypeSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public FormulaTypeSetting Get(int key) => _dataMap[key];
    public FormulaTypeSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

