
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class FormulaTypeSetting : Luban.BeanBase
{
    public FormulaTypeSetting(JSONNode _buf) 
    {
        { if(!_buf["FormulaID"].IsNumber) { throw new SerializationException(); }  FormulaID = _buf["FormulaID"]; }
        { if(!_buf["ResourceFormulaType"].IsNumber) { throw new SerializationException(); }  ResourceFormulaType = _buf["ResourceFormulaType"]; }
        { if(!_buf["AttributeTypeJoin"].IsNumber) { throw new SerializationException(); }  AttributeTypeJoin = _buf["AttributeTypeJoin"]; }
        { if(!_buf["VitalTypeJoin"].IsNumber) { throw new SerializationException(); }  VitalTypeJoin = _buf["VitalTypeJoin"]; }
    }

    public static FormulaTypeSetting DeserializeFormulaTypeSetting(JSONNode _buf)
    {
        return new FormulaTypeSetting(_buf);
    }

    /// <summary>
    /// 公式ID
    /// </summary>
    public readonly int FormulaID;
    /// <summary>
    /// 公式类型
    /// </summary>
    public readonly int ResourceFormulaType;
    /// <summary>
    /// 属性输入
    /// </summary>
    public readonly int AttributeTypeJoin;
    /// <summary>
    /// 资源输入
    /// </summary>
    public readonly int VitalTypeJoin;
   
    public const int __ID__ = 939505808;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "FormulaID:" + FormulaID + ","
        + "ResourceFormulaType:" + ResourceFormulaType + ","
        + "AttributeTypeJoin:" + AttributeTypeJoin + ","
        + "VitalTypeJoin:" + VitalTypeJoin + ","
        + "}";
    }
}
}

