
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum HitReactionType
    {
        /// <summary>
        /// 轻受击：扣血/闪白/顿帧，不断招
        /// </summary>
        Light = 0,
        /// <summary>
        /// 重受击：短硬直并断招
        /// </summary>
        Heavy = 1,
    }

} 

