
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum ModifyType
    {
        /// <summary>
        /// //无调整
        /// </summary>
        None = 0,
        /// <summary>
        /// //基础值调整
        /// </summary>
        Add = 1,
        /// <summary>
        /// //百分比调整
        /// </summary>
        PctAdd = 2,
        /// <summary>
        /// //重新设置基础值
        /// </summary>
        SetBase = 3,
    }

} 

