
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public partial class RoleAttriReader
{
    private readonly System.Collections.Generic.Dictionary<int, RoleAttriSetting> _dataMap;
    private readonly System.Collections.Generic.List<RoleAttriSetting> _dataList;
    
    public RoleAttriReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, RoleAttriSetting>(count);
        _dataList = new System.Collections.Generic.List<RoleAttriSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RoleAttriSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.RoleAttriSetting.DeserializeRoleAttriSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RoleAttriSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<RoleAttriSetting> DataList => _dataList;

    public RoleAttriSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RoleAttriSetting Get(int key) => _dataMap[key];
    public RoleAttriSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

