
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class RoleAttriSetting : Luban.BeanBase
{
    public RoleAttriSetting(JSONNode _buf) 
    {
        { if(!_buf["CharacterId"].IsNumber) { throw new SerializationException(); }  CharacterId = _buf["CharacterId"]; }
        { if(!_buf["baseHealthPointMax"].IsNumber) { throw new SerializationException(); }  BaseHealthPointMax = _buf["baseHealthPointMax"]; }
        { if(!_buf["HealthPointMaxAdd"].IsNumber) { throw new SerializationException(); }  HealthPointMaxAdd = _buf["HealthPointMaxAdd"]; }
        { if(!_buf["baseAttack"].IsNumber) { throw new SerializationException(); }  BaseAttack = _buf["baseAttack"]; }
        { if(!_buf["AttackAdd"].IsNumber) { throw new SerializationException(); }  AttackAdd = _buf["AttackAdd"]; }
        { if(!_buf["baseDefense"].IsNumber) { throw new SerializationException(); }  BaseDefense = _buf["baseDefense"]; }
        { if(!_buf["DefenseAdd"].IsNumber) { throw new SerializationException(); }  DefenseAdd = _buf["DefenseAdd"]; }
        { if(!_buf["baseManaMax"].IsNumber) { throw new SerializationException(); }  BaseManaMax = _buf["baseManaMax"]; }
        { if(!_buf["ManaMaxAdd"].IsNumber) { throw new SerializationException(); }  ManaMaxAdd = _buf["ManaMaxAdd"]; }
        { if(!_buf["baseCriticalProbability"].IsNumber) { throw new SerializationException(); }  BaseCriticalProbability = _buf["baseCriticalProbability"]; }
        { if(!_buf["CriticalProbabilityAdd"].IsNumber) { throw new SerializationException(); }  CriticalProbabilityAdd = _buf["CriticalProbabilityAdd"]; }
        { if(!_buf["baseCriticalValue"].IsNumber) { throw new SerializationException(); }  BaseCriticalValue = _buf["baseCriticalValue"]; }
        { if(!_buf["CriticalValueAdd"].IsNumber) { throw new SerializationException(); }  CriticalValueAdd = _buf["CriticalValueAdd"]; }
    }

    public static RoleAttriSetting DeserializeRoleAttriSetting(JSONNode _buf)
    {
        return new RoleAttriSetting(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int CharacterId;
    /// <summary>
    /// 基础血量上限
    /// </summary>
    public readonly int BaseHealthPointMax;
    /// <summary>
    /// 血量上限增长值
    /// </summary>
    public readonly float HealthPointMaxAdd;
    /// <summary>
    /// 基础攻击力
    /// </summary>
    public readonly int BaseAttack;
    /// <summary>
    /// 攻击力增长值
    /// </summary>
    public readonly float AttackAdd;
    /// <summary>
    /// 基础防御力
    /// </summary>
    public readonly int BaseDefense;
    /// <summary>
    /// 防御力增长值
    /// </summary>
    public readonly float DefenseAdd;
    /// <summary>
    /// 基础能量上限
    /// </summary>
    public readonly int BaseManaMax;
    /// <summary>
    /// 能量上限增长值
    /// </summary>
    public readonly float ManaMaxAdd;
    /// <summary>
    /// 基础暴击率（万分比）
    /// </summary>
    public readonly int BaseCriticalProbability;
    /// <summary>
    /// 暴击率增长值（万分比）
    /// </summary>
    public readonly float CriticalProbabilityAdd;
    /// <summary>
    /// 基础暴击倍率（万分比）
    /// </summary>
    public readonly int BaseCriticalValue;
    /// <summary>
    /// 暴击倍率增长值（万分比）
    /// </summary>
    public readonly float CriticalValueAdd;
   
    public const int __ID__ = 848199246;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CharacterId:" + CharacterId + ","
        + "baseHealthPointMax:" + BaseHealthPointMax + ","
        + "HealthPointMaxAdd:" + HealthPointMaxAdd + ","
        + "baseAttack:" + BaseAttack + ","
        + "AttackAdd:" + AttackAdd + ","
        + "baseDefense:" + BaseDefense + ","
        + "DefenseAdd:" + DefenseAdd + ","
        + "baseManaMax:" + BaseManaMax + ","
        + "ManaMaxAdd:" + ManaMaxAdd + ","
        + "baseCriticalProbability:" + BaseCriticalProbability + ","
        + "CriticalProbabilityAdd:" + CriticalProbabilityAdd + ","
        + "baseCriticalValue:" + BaseCriticalValue + ","
        + "CriticalValueAdd:" + CriticalValueAdd + ","
        + "}";
    }
}
}

