
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace EGamePlay.Combat
{ 
    public enum SkillCategory
    {
        /// <summary>
        /// 未分类
        /// </summary>
        None = 0,
        /// <summary>
        /// 普攻连段
        /// </summary>
        BasicAttack = 1,
        /// <summary>
        /// 蓄力
        /// </summary>
        HeavyAttack = 2,
        /// <summary>
        /// 冲刺攻击
        /// </summary>
        DashAttack = 3,
        /// <summary>
        /// 闪避反击
        /// </summary>
        DodgeCounter = 4,
        /// <summary>
        /// 闪避
        /// </summary>
        Dodge = 5,
        /// <summary>
        /// 战技
        /// </summary>
        Special = 6,
        /// <summary>
        /// EX 战技
        /// </summary>
        ExSpecial = 7,
        /// <summary>
        /// 终结技
        /// </summary>
        Ultimate = 8,
        /// <summary>
        /// 连携
        /// </summary>
        Chain = 9,
        /// <summary>
        /// 快速支援
        /// </summary>
        QuickAssist = 10,
        /// <summary>
        /// 防御支援/招架
        /// </summary>
        DefensiveAssist = 11,
        /// <summary>
        /// 回避支援
        /// </summary>
        EvasiveAssist = 12,
        /// <summary>
        /// 支援突击
        /// </summary>
        AssistFollowUp = 13,
        /// <summary>
        /// 核心被动
        /// </summary>
        CorePassive = 14,
        /// <summary>
        /// 额外能力
        /// </summary>
        AdditionalAbility = 15,
        /// <summary>
        /// 轴窗边分支
        /// </summary>
        Branch = 16,
        /// <summary>
        /// 敌人主动技
        /// </summary>
        EnemyActive = 17,
        HarmonyBreak = 18,
    }

} 

