
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class SkillDamageSetting : Luban.BeanBase
{
    public SkillDamageSetting(JSONNode _buf) 
    {
        { if(!_buf["SkillId"].IsNumber) { throw new SerializationException(); }  SkillId = _buf["SkillId"]; }
        { if(!_buf["SkillName"].IsString) { throw new SerializationException(); }  SkillName = _buf["SkillName"]; }
        { if(!_buf["SegmentIndex"].IsNumber) { throw new SerializationException(); }  SegmentIndex = _buf["SegmentIndex"]; }
        { if(!_buf["Ratio"].IsNumber) { throw new SerializationException(); }  Ratio = _buf["Ratio"]; }
        { if(!_buf["DamageType"].IsNumber) { throw new SerializationException(); }  DamageType = (DamageType)_buf["DamageType"].AsInt; }
        { if(!_buf["FormulaType"].IsNumber) { throw new SerializationException(); }  FormulaType = _buf["FormulaType"]; }
        { if(!_buf["CanCrit"].IsNumber) { throw new SerializationException(); }  CanCrit = _buf["CanCrit"]; }
    }

    public static SkillDamageSetting DeserializeSkillDamageSetting(JSONNode _buf)
    {
        return new SkillDamageSetting(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string SkillName;
    /// <summary>
    /// 伤害段数
    /// </summary>
    public readonly int SegmentIndex;
    /// <summary>
    /// 伤害系数
    /// </summary>
    public readonly float Ratio;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly DamageType DamageType;
    /// <summary>
    /// 结算公式
    /// </summary>
    public readonly int FormulaType;
    /// <summary>
    /// 是否支持暴击
    /// </summary>
    public readonly int CanCrit;
   
    public const int __ID__ = -527803088;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SkillId:" + SkillId + ","
        + "SkillName:" + SkillName + ","
        + "SegmentIndex:" + SegmentIndex + ","
        + "Ratio:" + Ratio + ","
        + "DamageType:" + DamageType + ","
        + "FormulaType:" + FormulaType + ","
        + "CanCrit:" + CanCrit + ","
        + "}";
    }
}
}

