
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public partial class SkillDamageReader
{
    private readonly System.Collections.Generic.List<SkillDamageSetting> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), SkillDamageSetting> _dataMapUnion;

    public SkillDamageReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<SkillDamageSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SkillDamageSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.SkillDamageSetting.DeserializeSkillDamageSetting(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), SkillDamageSetting>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.SkillId, _v.SegmentIndex), _v);
        }
    }

    public System.Collections.Generic.List<SkillDamageSetting> DataList => _dataList;

    public SkillDamageSetting Get(int SkillId, int SegmentIndex) => _dataMapUnion.TryGetValue((SkillId, SegmentIndex), out SkillDamageSetting __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

