
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class SkillDemoSetting : Luban.BeanBase
{
    public SkillDemoSetting(JSONNode _buf) 
    {
        { if(!_buf["SkillId"].IsNumber) { throw new SerializationException(); }  SkillId = _buf["SkillId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Type"].IsString) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["TargetGroup"].IsNumber) { throw new SerializationException(); }  TargetGroup = _buf["TargetGroup"]; }
        { if(!_buf["TargetSelect"].IsNumber) { throw new SerializationException(); }  TargetSelect = _buf["TargetSelect"]; }
        { if(!_buf["Cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["Cooldown"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["TriggerFormula"].IsString) { throw new SerializationException(); }  TriggerFormula = _buf["TriggerFormula"]; }
        { var __json0 = _buf["RequiredTags"]; if(!__json0.IsArray) { throw new SerializationException(); } RequiredTags = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  RequiredTags.Add(__v0); }   }
        { var __json0 = _buf["BlockedTags"]; if(!__json0.IsArray) { throw new SerializationException(); } BlockedTags = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  BlockedTags.Add(__v0); }   }
        { var __json0 = _buf["EffectIds"]; if(!__json0.IsArray) { throw new SerializationException(); } EffectIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EffectIds.Add(__v0); }   }
        { var __json0 = _buf["InlineBuffEffectIds"]; if(!__json0.IsArray) { throw new SerializationException(); } InlineBuffEffectIds = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  InlineBuffEffectIds.Add(__v0); }   }
        { if(!_buf["CostFormulaType"].IsNumber) { throw new SerializationException(); }  CostFormulaType = _buf["CostFormulaType"]; }
        { if(!_buf["CostAttrType"].IsNumber) { throw new SerializationException(); }  CostAttrType = _buf["CostAttrType"]; }
        { if(!_buf["CostA"].IsNumber) { throw new SerializationException(); }  CostA = _buf["CostA"]; }
        { if(!_buf["CostB"].IsNumber) { throw new SerializationException(); }  CostB = _buf["CostB"]; }
    }

    public static SkillDemoSetting DeserializeSkillDemoSetting(JSONNode _buf)
    {
        return new SkillDemoSetting(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 能力类型
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// 目标阵营
    /// </summary>
    public readonly int TargetGroup;
    /// <summary>
    /// 目标选择方式
    /// </summary>
    public readonly int TargetSelect;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 技能描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 技能释放判断
    /// </summary>
    public readonly string TriggerFormula;
    /// <summary>
    /// 技能释放所需标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> RequiredTags;
    /// <summary>
    /// 技能释放不能有的标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> BlockedTags;
    /// <summary>
    /// 技能效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> EffectIds;
    /// <summary>
    /// 技能效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> InlineBuffEffectIds;
    /// <summary>
    /// 消耗公式
    /// </summary>
    public readonly int CostFormulaType;
    /// <summary>
    /// 消耗属性
    /// </summary>
    public readonly int CostAttrType;
    /// <summary>
    /// 公式的A部分
    /// </summary>
    public readonly float CostA;
    /// <summary>
    /// 公式的B部分
    /// </summary>
    public readonly float CostB;
   
    public const int __ID__ = 642189308;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SkillId:" + SkillId + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "TargetGroup:" + TargetGroup + ","
        + "TargetSelect:" + TargetSelect + ","
        + "Cooldown:" + Cooldown + ","
        + "Description:" + Description + ","
        + "TriggerFormula:" + TriggerFormula + ","
        + "RequiredTags:" + Luban.StringUtil.CollectionToString(RequiredTags) + ","
        + "BlockedTags:" + Luban.StringUtil.CollectionToString(BlockedTags) + ","
        + "EffectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "InlineBuffEffectIds:" + Luban.StringUtil.CollectionToString(InlineBuffEffectIds) + ","
        + "CostFormulaType:" + CostFormulaType + ","
        + "CostAttrType:" + CostAttrType + ","
        + "CostA:" + CostA + ","
        + "CostB:" + CostB + ","
        + "}";
    }
}
}

