
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public partial class SkillDemoReader
{
    private readonly System.Collections.Generic.Dictionary<int, SkillDemoSetting> _dataMap;
    private readonly System.Collections.Generic.List<SkillDemoSetting> _dataList;
    
    public SkillDemoReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillDemoSetting>(count);
        _dataList = new System.Collections.Generic.List<SkillDemoSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SkillDemoSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.SkillDemoSetting.DeserializeSkillDemoSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.SkillId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillDemoSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillDemoSetting> DataList => _dataList;

    public SkillDemoSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SkillDemoSetting Get(int key) => _dataMap[key];
    public SkillDemoSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

