
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
public sealed partial class SquadSetting : Luban.BeanBase
{
    public SquadSetting(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["SwitchLock"].IsNumber) { throw new SerializationException(); }  SwitchLock = _buf["SwitchLock"]; }
        { if(!_buf["AssistWindow"].IsNumber) { throw new SerializationException(); }  AssistWindow = _buf["AssistWindow"]; }
        { if(!_buf["AssistPointsMax"].IsNumber) { throw new SerializationException(); }  AssistPointsMax = _buf["AssistPointsMax"]; }
        { if(!_buf["AssistPointRegenPerSec"].IsNumber) { throw new SerializationException(); }  AssistPointRegenPerSec = _buf["AssistPointRegenPerSec"]; }
        { if(!_buf["SwitchIFrame"].IsNumber) { throw new SerializationException(); }  SwitchIFrame = _buf["SwitchIFrame"]; }
        { if(!_buf["AssistPointDefensiveCost"].IsNumber) { throw new SerializationException(); }  AssistPointDefensiveCost = _buf["AssistPointDefensiveCost"]; }
        { if(!_buf["AssistPointEvasiveCost"].IsNumber) { throw new SerializationException(); }  AssistPointEvasiveCost = _buf["AssistPointEvasiveCost"]; }
    }

    public static SquadSetting DeserializeSquadSetting(JSONNode _buf)
    {
        return new SquadSetting(_buf);
    }

    /// <summary>
    /// 档位
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 仅 Manual 表现锁秒
    /// </summary>
    public readonly float SwitchLock;
    /// <summary>
    /// 快速支援窗秒
    /// </summary>
    public readonly float AssistWindow;
    /// <summary>
    /// 支援点上限
    /// </summary>
    public readonly int AssistPointsMax;
    /// <summary>
    /// 每秒回复
    /// </summary>
    public readonly float AssistPointRegenPerSec;
    /// <summary>
    /// 换入 i-frame 秒
    /// </summary>
    public readonly float SwitchIFrame;
    /// <summary>
    /// 黄闪耗点
    /// </summary>
    public readonly int AssistPointDefensiveCost;
    /// <summary>
    /// 红闪耗点
    /// </summary>
    public readonly int AssistPointEvasiveCost;
   
    public const int __ID__ = 2023191766;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SwitchLock:" + SwitchLock + ","
        + "AssistWindow:" + AssistWindow + ","
        + "AssistPointsMax:" + AssistPointsMax + ","
        + "AssistPointRegenPerSec:" + AssistPointRegenPerSec + ","
        + "SwitchIFrame:" + SwitchIFrame + ","
        + "AssistPointDefensiveCost:" + AssistPointDefensiveCost + ","
        + "AssistPointEvasiveCost:" + AssistPointEvasiveCost + ","
        + "}";
    }
}
}

