
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace EGamePlay.Combat
{
/// <summary>
/// 小队换人：支援窗 / 支援点 / i-frame
/// </summary>
public partial class SquadSettingReader
{
    private readonly System.Collections.Generic.Dictionary<int, SquadSetting> _dataMap;
    private readonly System.Collections.Generic.List<SquadSetting> _dataList;
    
    public SquadSettingReader(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SquadSetting>(count);
        _dataList = new System.Collections.Generic.List<SquadSetting>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SquadSetting _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::EGamePlay.Combat.SquadSetting.DeserializeSquadSetting(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SquadSetting> DataMap => _dataMap;
    public System.Collections.Generic.List<SquadSetting> DataList => _dataList;

    public SquadSetting GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SquadSetting Get(int key) => _dataMap[key];
    public SquadSetting this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

