
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace EGamePlay.Combat
{
public partial class Tables
{
    public SkillDemoReader SkillDemoReader {get; }
    public SkillDamageReader SkillDamageReader {get; }
    public BuffDemoReader BuffDemoReader {get; }
    public BuffModifyReader BuffModifyReader {get; }
    public FormulaTypeReader FormulaTypeReader {get; }
    public RoleAttriReader RoleAttriReader {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        SkillDemoReader = new SkillDemoReader(loader("skilldemoreader"));
        SkillDamageReader = new SkillDamageReader(loader("skilldamagereader"));
        BuffDemoReader = new BuffDemoReader(loader("buffdemoreader"));
        BuffModifyReader = new BuffModifyReader(loader("buffmodifyreader"));
        FormulaTypeReader = new FormulaTypeReader(loader("formulatypereader"));
        RoleAttriReader = new RoleAttriReader(loader("roleattrireader"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        SkillDemoReader.ResolveRef(this);
        SkillDamageReader.ResolveRef(this);
        BuffDemoReader.ResolveRef(this);
        BuffModifyReader.ResolveRef(this);
        FormulaTypeReader.ResolveRef(this);
        RoleAttriReader.ResolveRef(this);
    }
}

}
