
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace EGamePlay.Combat
{
public partial class Tables
{
    public SkillDemoReader SkillDemoReader {get; }
    public SkillDamageReader SkillDamageReader {get; }
    public BuffDemoReader BuffDemoReader {get; }
    public BuffModifyReader BuffModifyReader {get; }
    public FormulaTypeReader FormulaTypeReader {get; }
    public RoleAttriReader RoleAttriReader {get; }
    public DazeSettingReader DazeSettingReader {get; }
    /// <summary>
    /// 角色招式包：被动 + Z 响应技
    /// </summary>
    public CharacterKitReader CharacterKitReader {get; }
    /// <summary>
    /// 角色 4 战斗键 Idle 入口
    /// </summary>
    public CharacterSlotReader CharacterSlotReader {get; }
    /// <summary>
    /// 小队换人：支援窗 / 支援点 / i-frame
    /// </summary>
    public SquadSettingReader SquadSettingReader {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        SkillDemoReader = new SkillDemoReader(loader("skilldemoreader"));
        SkillDamageReader = new SkillDamageReader(loader("skilldamagereader"));
        BuffDemoReader = new BuffDemoReader(loader("buffdemoreader"));
        BuffModifyReader = new BuffModifyReader(loader("buffmodifyreader"));
        FormulaTypeReader = new FormulaTypeReader(loader("formulatypereader"));
        RoleAttriReader = new RoleAttriReader(loader("roleattrireader"));
        DazeSettingReader = new DazeSettingReader(loader("dazesettingreader"));
        CharacterKitReader = new CharacterKitReader(loader("characterkitreader"));
        CharacterSlotReader = new CharacterSlotReader(loader("characterslotreader"));
        SquadSettingReader = new SquadSettingReader(loader("squadsettingreader"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        SkillDemoReader.ResolveRef(this);
        SkillDamageReader.ResolveRef(this);
        BuffDemoReader.ResolveRef(this);
        BuffModifyReader.ResolveRef(this);
        FormulaTypeReader.ResolveRef(this);
        RoleAttriReader.ResolveRef(this);
        DazeSettingReader.ResolveRef(this);
        CharacterKitReader.ResolveRef(this);
        CharacterSlotReader.ResolveRef(this);
        SquadSettingReader.ResolveRef(this);
    }
}

}
